-- Supabase schema for App de Inventário

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name1 text not null,
  name2 text not null,
  alt_team_id bigint references public.teams(id) on delete set null,
  created_at timestamptz default now()
);

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  assigned_team_id bigint not null references public.teams(id) on delete cascade,
  name text not null,
  base_quantity integer not null,
  attempts integer not null default 0,
  resolved boolean not null default false,
  removed boolean not null default false,
  created_at timestamptz default now()
);
