-- Create master inventory table and assignments; redistribute items randomly when teams change

create table if not exists public.master_inventory_items (
  id bigint generated by default as identity primary key,
  planta text,
  classe text,
  material text,
  descricao text,
  base_quantity numeric,
  umb text,
  pos_dpst text,
  dep text,
  desc_deposito text,
  created_at timestamptz default now()
);

create table if not exists public.team_item_assignments (
  id bigint generated by default as identity primary key,
  master_item_id bigint not null references public.master_inventory_items(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  found_quantity numeric,
  attempts integer not null default 0,
  resolved boolean not null default false,
  removed boolean not null default false,
  created_at timestamptz default now(),
  unique(master_item_id, team_id)
);

-- Function: redistribute all master items randomly across existing teams
create or replace function public.redistribute_master_items() returns void language plpgsql security definer as $$
declare
  team_count integer;
begin
  select count(*) into team_count from public.teams;
  if team_count = 0 then
    -- no teams: clear assignments
    delete from public.team_item_assignments;
    return;
  end if;

  -- remove old assignments and reassign randomly and as-evenly-as-possible
  delete from public.team_item_assignments;

  with teams as (
    select id, row_number() over (order by id) as tnum from public.teams
  ),
  items as (
    select id, row_number() over (order by random()) as mnum from public.master_inventory_items
  )
  insert into public.team_item_assignments (master_item_id, team_id, found_quantity, attempts, resolved, removed, created_at)
  select i.id as master_item_id,
         t.id as team_id,
      null::numeric as found_quantity,
         0 as attempts,
         false as resolved,
         false as removed,
         now() as created_at
  from items i
  join teams t on (((i.mnum - 1) % team_count) + 1) = t.tnum;
end; $$;

-- Trigger: when a new team is inserted, redistribute items
create or replace function public.on_team_insert_trigger() returns trigger language plpgsql security definer as $$
begin
  perform public.redistribute_master_items();
  return new;
end; $$;

drop trigger if exists trg_redistribute_on_team_insert on public.teams;
create trigger trg_redistribute_on_team_insert
  after insert on public.teams
  for each row
  execute function public.on_team_insert_trigger();

-- View: get items for a team (includes base_quantity from master and found_quantity from assignment)
create or replace view public.view_items_for_team as
select a.id as assignment_id,
       a.team_id,
       m.id as master_item_id,
       m.descricao,
       m.material,
       m.base_quantity,
       m.umb,
       a.found_quantity,
       a.attempts,
       a.resolved,
       a.removed
from public.team_item_assignments a
join public.master_inventory_items m on m.id = a.master_item_id;

-- Usage notes (for operator):
-- 1) Import your CSV into `public.master_inventory_items` using Supabase UI or psql COPY:
--    psql "postgresql://<user>:<pass>@<host>:5432/<db>" -c "\copy public.master_inventory_items(planta,classe,material,descricao,base_quantity,umb,pos_dpst,dep,desc_deposito) FROM 'prateleiras_almox.csv' WITH CSV HEADER"
--    (Adjust column list to match CSV order; columns not present will be left NULL.)
-- 2) After importing, call the redistribute function once to populate `team_item_assignments`:
--    SELECT public.redistribute_master_items();
-- 3) When a user wants items for a team, query the view:
--    SELECT * FROM public.view_items_for_team WHERE team_id = <team_id>;
-- 4) When the user reports the found quantity for an item, update `team_item_assignments.found_quantity` for the assignment id.
