-- Cria o cadastro mestre, as atribuições e a redistribuição dos itens entre equipes.

-- Cadastro único dos materiais importados do inventário oficial.
create table if not exists public.master_inventory_items (
  id bigint generated by default as identity primary key,
  planta text,
  classe text,
  material text,
  descricao text,
  base_quantity numeric,
  umb text,
  pos_dpst text,
  dep text,
  desc_deposito text,
  created_at timestamptz default now()
);

-- Representa a atribuição atual de cada item a uma equipe.
create table if not exists public.team_item_assignments (
  id bigint generated by default as identity primary key,
  master_item_id bigint not null references public.master_inventory_items(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  found_quantity numeric,
  attempts integer not null default 0,
  resolved boolean not null default false,
  removed boolean not null default false,
  created_at timestamptz default now(),
  unique(master_item_id, team_id)
);

-- Redistribui todos os itens mestres de forma equilibrada e aleatória entre as equipes.
create or replace function public.redistribute_master_items() returns void language plpgsql security definer as $$
declare
  team_count integer;
begin
  select count(*) into team_count from public.teams;
  if team_count = 0 then
    -- Sem equipes: limpa as atribuições.
    delete from public.team_item_assignments;
    return;
  end if;

  -- Remove as atribuições antigas e redistribui os itens de forma equilibrada.
  delete from public.team_item_assignments;

  with teams as (
    select id, row_number() over (order by id) as tnum from public.teams
  ),
  items as (
    select id, row_number() over (order by random()) as mnum from public.master_inventory_items
  )
  insert into public.team_item_assignments (master_item_id, team_id, found_quantity, attempts, resolved, removed, created_at)
  select i.id as master_item_id,
         t.id as team_id,
      null::numeric as found_quantity,
         0 as attempts,
         false as resolved,
         false as removed,
         now() as created_at
  from items i
  join teams t on (((i.mnum - 1) % team_count) + 1) = t.tnum;
end; $$;

-- Função chamada automaticamente quando uma nova equipe é criada.
create or replace function public.on_team_insert_trigger() returns trigger language plpgsql security definer as $$
begin
  perform public.redistribute_master_items();
  return new;
end; $$;

-- Trigger que dispara a redistribuição depois da inclusão de uma equipe.
drop trigger if exists trg_redistribute_on_team_insert on public.teams;
create trigger trg_redistribute_on_team_insert
  after insert on public.teams
  for each row
  execute function public.on_team_insert_trigger();

-- View que combina dados do material mestre com sua atribuição atual.
create or replace view public.view_items_for_team as
select a.id as assignment_id,
       a.team_id,
       m.id as master_item_id,
       m.descricao,
       m.material,
       m.base_quantity,
       m.umb,
       a.found_quantity,
       a.attempts,
       a.resolved,
       a.removed
from public.team_item_assignments a
join public.master_inventory_items m on m.id = a.master_item_id;

-- Operação: após importar materiais, execute redistribute_master_items() para criar as atribuições.
-- 1) Importe o CSV para `public.master_inventory_items` usando a interface do Supabase ou COPY do psql:
--    psql "postgresql://<user>:<pass>@<host>:5432/<db>" -c "\copy public.master_inventory_items(planta,classe,material,descricao,base_quantity,umb,pos_dpst,dep,desc_deposito) FROM 'prateleiras_almox.csv' WITH CSV HEADER"
--    (Ajuste a lista de colunas conforme a ordem do CSV; colunas ausentes ficarão NULL.)
-- 2) Depois da importação, execute a função de redistribuição para preencher `team_item_assignments`:
--    SELECT public.redistribute_master_items();
-- 3) Para consultar os itens de uma equipe, consulte a view:
--    SELECT * FROM public.view_items_for_team WHERE team_id = <team_id>;
-- 4) Ao informar a quantidade encontrada, atualize `team_item_assignments.found_quantity` pelo ID da atribuição.
