-- Registra cada contagem e movimenta o item quando a quantidade estiver incorreta.

-- Histórico de todas as tentativas de contagem feitas pelas equipes.
create table if not exists public.team_item_counts (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.team_item_assignments(id) on delete cascade,
  master_item_id bigint not null references public.master_inventory_items(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  attempt_number integer not null,
  entered_quantity numeric,
  base_quantity numeric,
  created_at timestamptz default now()
);

-- Trigger que registra a tentativa, resolve o item ou o envia para a próxima equipe.
create or replace function public.handle_found_quantity_update() returns trigger language plpgsql security definer as $$
declare
  base_qty numeric;
  new_attempt integer;
  team_ids bigint[];
  team_count integer;
  cur_idx integer := 0;
  next_team_id bigint;
  i integer;
begin
  -- Evita que as atualizações feitas pela própria função disparem o trigger novamente.
  if pg_trigger_depth() > 1 then
    return new;
  end if;

  -- Só processa alterações reais para uma quantidade não nula.
  if new.found_quantity is null then
    return new;
  end if;
  if old.found_quantity is not distinct from new.found_quantity then
    return new;
  end if;

  select base_quantity into base_qty from public.master_inventory_items where id = new.master_item_id;
  new_attempt := coalesce(new.attempts, 0) + 1;

  insert into public.team_item_counts(assignment_id, master_item_id, team_id, attempt_number, entered_quantity, base_quantity, created_at)
    values (new.id, new.master_item_id, new.team_id, new_attempt, new.found_quantity, base_qty, now());

  update public.team_item_assignments set attempts = new_attempt where id = new.id;

  -- Quantidade correta: marca a atribuição como resolvida.
  if base_qty is not null and new.found_quantity = base_qty then
    update public.team_item_assignments set resolved = true where id = new.id;
    return new;
  end if;

  -- Após quatro tentativas, encerra o processo sem nova redistribuição.
  if new_attempt >= 4 then
    update public.team_item_assignments set resolved = true where id = new.id;
    return new;
  end if;

  -- Busca as equipes em ordem determinística para escolher a próxima.
  select array_agg(id order by id) into team_ids from public.teams;
  team_count := array_length(team_ids, 1);
  if team_count is null or team_count = 0 then
    return new;
  end if;

  for i in 1..team_count loop
    if team_ids[i] = new.team_id then
      cur_idx := i;
      exit;
    end if;
  end loop;
  if cur_idx = 0 then
    cur_idx := 1;
  end if;
  next_team_id := team_ids[((cur_idx % team_count) + 1)];

  -- Move a atribuição e limpa a quantidade para a próxima equipe registrar novamente.
  update public.team_item_assignments
    set team_id = next_team_id,
        found_quantity = null
  where id = new.id;

  return new;
end; $$;

drop trigger if exists trg_handle_found_quantity on public.team_item_assignments;
create trigger trg_handle_found_quantity
  after update of found_quantity on public.team_item_assignments
  for each row
  when (old.found_quantity is distinct from new.found_quantity)
  execute function public.handle_found_quantity_update();

-- Observação: o histórico fica em team_item_counts e a lista atual vem de view_items_for_team.
-- - Quando um usuário atualiza `team_item_assignments.found_quantity`, o trigger registra a tentativa em
--   `team_item_counts` e, se o valor não corresponder a `base_quantity`, move a atribuição para a próxima
--   equipe. Após quatro tentativas, a atribuição é marcada como resolvida.
-- - Use `view_items_for_team` para listar os itens atuais de uma equipe; as tentativas ficam em
--   `team_item_counts`.
