-- Migration: add count history and trigger to move item to next team on mismatch

create table if not exists public.team_item_counts (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.team_item_assignments(id) on delete cascade,
  master_item_id bigint not null references public.master_inventory_items(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  attempt_number integer not null,
  entered_quantity numeric,
  base_quantity numeric,
  created_at timestamptz default now()
);

-- Function to record the count and progress the assignment to the next team when needed
create or replace function public.handle_found_quantity_update() returns trigger language plpgsql security definer as $$
declare
  base_qty numeric;
  new_attempt integer;
  team_ids bigint[];
  team_count integer;
  cur_idx integer := 0;
  next_team_id bigint;
  i integer;
begin
  -- avoid recursive trigger runs
  if pg_trigger_depth() > 1 then
    return new;
  end if;

  -- only proceed when found_quantity changed to a non-null value
  if new.found_quantity is null then
    return new;
  end if;
  if old.found_quantity is not distinct from new.found_quantity then
    return new;
  end if;

  select base_quantity into base_qty from public.master_inventory_items where id = new.master_item_id;
  new_attempt := coalesce(new.attempts, 0) + 1;

  insert into public.team_item_counts(assignment_id, master_item_id, team_id, attempt_number, entered_quantity, base_quantity, created_at)
    values (new.id, new.master_item_id, new.team_id, new_attempt, new.found_quantity, base_qty, now());

  update public.team_item_assignments set attempts = new_attempt where id = new.id;

  -- if found matches base_quantity => mark resolved and stop
  if base_qty is not null and new.found_quantity = base_qty then
    update public.team_item_assignments set resolved = true where id = new.id;
    return new;
  end if;

  -- if reached 4 attempts, mark resolved (stop further reassignments)
  if new_attempt >= 4 then
    update public.team_item_assignments set resolved = true where id = new.id;
    return new;
  end if;

  -- get teams in deterministic order and pick next team
  select array_agg(id order by id) into team_ids from public.teams;
  team_count := array_length(team_ids, 1);
  if team_count is null or team_count = 0 then
    return new;
  end if;

  for i in 1..team_count loop
    if team_ids[i] = new.team_id then
      cur_idx := i;
      exit;
    end if;
  end loop;
  if cur_idx = 0 then
    cur_idx := 1;
  end if;
  next_team_id := team_ids[((cur_idx % team_count) + 1)];

  -- move assignment to next team and clear found_quantity for the next inspector
  update public.team_item_assignments
    set team_id = next_team_id,
        found_quantity = null
  where id = new.id;

  return new;
end; $$;

drop trigger if exists trg_handle_found_quantity on public.team_item_assignments;
create trigger trg_handle_found_quantity
  after update of found_quantity on public.team_item_assignments
  for each row
  when (old.found_quantity is distinct from new.found_quantity)
  execute function public.handle_found_quantity_update();

-- Notes:
-- - When an inspector updates `team_item_assignments.found_quantity`, the trigger will record the attempt in
--   `team_item_counts` and, if the value does not match the master `base_quantity`, move the assignment to the next
--   team (wrap-around). After 4 attempts the assignment is marked `resolved` to stop further rotations.
-- - Use `view_items_for_team` (created earlier) to list current items for a team; historical attempts are in
--   `team_item_counts`.
