-- Reaplica o processamento das contagens no banco atualmente conectado ao aplicativo.
-- Execute este arquivo no SQL Editor do mesmo projeto Supabase usado em script.js.

-- Garante a tabela de histórico caso a migration anterior não tenha sido aplicada.
create table if not exists public.team_item_counts (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.team_item_assignments(id) on delete cascade,
  master_item_id bigint not null references public.master_inventory_items(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  attempt_number integer not null,
  entered_quantity numeric,
  base_quantity numeric,
  created_at timestamptz default now()
);

-- Registra a tentativa e encaminha o item para a equipe alternativa configurada.
create or replace function public.handle_found_quantity_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  base_qty numeric;
  new_attempt integer;
  next_team_id bigint;
begin
  -- Processa somente alterações reais para uma quantidade informada.
  if new.found_quantity is null
     or old.found_quantity is not distinct from new.found_quantity then
    return new;
  end if;

  select base_quantity
    into base_qty
    from public.master_inventory_items
   where id = new.master_item_id;

  new_attempt := coalesce(old.attempts, 0) + 1;

  insert into public.team_item_counts (
    assignment_id,
    master_item_id,
    team_id,
    attempt_number,
    entered_quantity,
    base_quantity
  ) values (
    new.id,
    new.master_item_id,
    new.team_id,
    new_attempt,
    new.found_quantity,
    base_qty
  );

  -- Atualiza a quantidade de tentativas antes de decidir o próximo estado.
  update public.team_item_assignments
     set attempts = new_attempt
   where id = new.id;

  -- Quantidade correta ou quarta tentativa: encerra o item.
  if (base_qty is not null and new.found_quantity = base_qty)
     or new_attempt >= 4 then
    update public.team_item_assignments
       set resolved = true
     where id = new.id;
    return new;
  end if;

  -- Usa a equipe alternativa configurada para a equipe atual.
  select alt_team_id
    into next_team_id
    from public.teams
   where id = new.team_id;

  -- Se não houver alternativa configurada, usa a próxima equipe por ID.
  if next_team_id is null or next_team_id = new.team_id then
    select id
      into next_team_id
      from public.teams
     where id <> new.team_id
     order by id
     limit 1;
  end if;

  -- Move o item e deixa a nova equipe pronta para uma nova contagem.
  if next_team_id is not null then
    update public.team_item_assignments
       set team_id = next_team_id,
           found_quantity = null
     where id = new.id;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_handle_found_quantity on public.team_item_assignments;

create trigger trg_handle_found_quantity
after update of found_quantity on public.team_item_assignments
for each row
when (old.found_quantity is distinct from new.found_quantity)
execute function public.handle_found_quantity_update();

-- Permite que o aplicativo registre o histórico usando a chave pública.
alter table public.team_item_counts enable row level security;

drop policy if exists "Allow insert team_item_counts" on public.team_item_counts;
create policy "Allow insert team_item_counts"
  on public.team_item_counts
  for insert
  to public
  with check (true);

drop policy if exists "Allow read team_item_counts" on public.team_item_counts;
create policy "Allow read team_item_counts"
  on public.team_item_counts
  for select
  to public
  using (true);
